### ISSUE TITLE
Request for additional data that reflects nutritional need within the states

### ISSUE THREAD

**Issue by JosephineCarenNdawula** [OxfordIHTM/ihtm-hackathon-2024#39]
@OxfordIHTM/neji 
#8 
If it is available, kindly provide us with additional data from the communities which can reflect nutritional needs in the community. Currently, we only have health facility data.

Thank you.

**Comment by ernestguevarra** [comment]
In the `maternal` dataset, you will see that there are variables called `muacPreviousMonth`, `muacPreviousThreeMonths`, `gmpCoverage`. When you look at the data dictionary for the child dataset, you will see that:

```R
                    field                                                                                      field_description
1       muacPreviousMonth                        Did the child get measured with a MUAC tape in the past month?: 1 = Yes; 0 = No
2 muacPreviousThreeMonths                 Did the child get measured with a MUAC tape in the past three months?: 1 = Yes; 0 = No
3             gmpCoverage Did the child's height and weight get measured in the healt clinci in the past month?: 1 = Yes; 0 = No
```

So, these field represent variables that can be analysed to get the prevalence of MUAC screening and general weight and height screening via GMP. These metrics for 2018 will generally be more robust than the routine monitoring data because the sample from the survey is a more representative sample and is not prone to the known issue of routine recording/counting of how many children have been screened (e.g., double counting, repeated measures).

**Comment by ernestguevarra** [comment]
I will close this issue now.
